TemplateEngine:
    Engines:
        Smarty:
            ForceCompile: true
            CacheDir: '/var/tmp/smarty/cache'
            CompileDir: '/var/tmp/smarty/compile'
            TemplateDir: '/tmp'
            AutoEscapeOutput: false
    # You can overwrite the default driver by providing your own.
    # How to create a new driver, read in the Readme.md file.
    # If you don't wish to change the default driver,
    # just ommit this definition in your config file.
    Bridges:
        Smarty: \Webiny\Component\TemplateEngine\Bridge\Smarty\Smarty
    ClassLoader:
        Smarty_:
            Path: '/var/www/projects/webiny/Vendors/Smarty/libs/sysplugins'
            Normalize: false
            Case: lower