name: EntityBuilder
version: 0.1.0
link: http://www.webiny.com/store/webiny/entity-builder/
description: The Entity Builder app provides users with interface for creating new entities.

authorName: Webiny LTD
authorLink: http://www.webiny.com
authorEmail: info@webiny.com