name: Core
version: 0.1.0
link: http://www.webiny.com/store/webiny/core/
description: The Core app provides the essential functions for Webiny platform.

authorName: Webiny LTD
authorLink: http://www.webiny.com
authorEmail: info@webiny.com