authorName: Webiny LTD
authorLink: http://www.webiny.com
authorEmail: info@webiny.com

appName: Core
appVersion: 0.1.0
appLink: http://www.webiny.com/store/webiny/core/
appDescription: The Core app provides the essential functions for Webiny platform.