author: Webiny LTD
author_link: http://www.webiny.com

app_name: Core
app_version: 0.1.0
app_link: http://www.webiny.com/store/webiny/core/
app_description: The Core app provides the essential functions for Webiny platform.