name: Developer
version: 0.1.0
link: http://www.webiny.com/store/webiny/developer/
description: The Developer app provides users with interface nd tools for creating new apps, plugins, components, etc.

authorName: Webiny LTD
authorLink: http://www.webiny.com
authorEmail: info@webiny.com